// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transaction_status_payload.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Pagination) Validate() error {
	return nil
}
func (this *GeneralBodyResponse) Validate() error {
	return nil
}
func (this *HealthCheckResponse) Validate() error {
	return nil
}
func (this *UserAuthority) Validate() error {
	return nil
}
func (this *RegisterJobTransactionPendingeRequest) Validate() error {
	return nil
}
func (this *RegisterJobTransactionPendingResponse) Validate() error {
	return nil
}
func (this *MassageRabbitPublish) Validate() error {
	return nil
}
func (this *UpdatedJobTransactionStatusRequest) Validate() error {
	return nil
}
func (this *UpdatedJobTransactionStatusResponse) Validate() error {
	return nil
}
